version: '3'
services:
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production-stage # 指定要使用的构建阶段
    container_name: myproject-frontend
    volumes:
      - ./frontend/project-hank02/public:/app/public
      - ./frontend/project-hank02/src:/app/src
    ports:
      - "3000:3000"
    networks:
      - app-network

  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
 