version: '3'
services:
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: vite-codux # 指定要使用的构建阶段
    container_name: myproject-frontend
    volumes:
      - ./frontend/ProjectVite01/src:/app/src
      - frontend_static:/app/dist
    ports:
      - "3000:3000"

    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl

    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  frontend_static:
 