version: '3'
services:
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: wabpack-codux
    container_name: myproject-frontend
    volumes:
      - ./frontend/project-hank02/src:/app/src
      - frontend_static:/app/dist
    ports:
      - "8080:8080"
    networks:
      - app-network
    #extra_hosts:
      #- "myapp.local:192.168.0.10
    
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - frontend_static:/app/static
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  frontend_static:
 