version: '3'
services:

  backend:
    build:
      context: ./backend
    container_name: myproject-backend
    volumes:
      - backend_static:/app/django_project/static
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend-build:
    build:
      context: ./frontend
    command: echo "frontend build complete"
    volumes:
      - ./frontend/dist:/app/frontend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/dist:/app/frontend
      - backend_static:/app/static
    depends_on:
      - backend
      - frontend-build
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_static:
