const { Document, Packer, Paragraph, Media, HeadingLevel } = require("docx");
const puppeteer = require("puppeteer");

module.exports = async (req, res) => {
  try {
    const input = req.body?.input || "No input provided.";
    const chartHtml = req.body?.chartHtml;

    if (!chartHtml) {
      console.warn("No chartHtml provided in request.");
      res.status(400).json({ error: "chartHtml is required" });
      return;
    }

    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || puppeteer.executablePath(),
    });

    const page = await browser.newPage();
    await page.setContent(chartHtml, { waitUntil: "networkidle0" });
    await page.waitForSelector("#marketShareChart, #growthChart").catch(() => {
      console.warn("Charts not rendered in time.");
    });

    await new Promise((resolve) => setTimeout(resolve, 1000));
    const chartBuffer = await page.screenshot({ type: "png" });
    await browser.close();

    // Creating the document without sections in the constructor
    const doc = new Document({
      creator: "Divorcepath API", // Creator of the document
      title: "Divorcepath Legal Report", // Title of the document
      description: "Legal report generated by Divorcepath API", // Description of the document
    });

    // Add a section to the document
    doc.addSection({
      children: [
        new Paragraph({
          text: "Divorcepath Legal Report",
          heading: HeadingLevel.HEADING_1, // Set as Heading 1
        }),
        new Paragraph("========================="),
        new Paragraph(input),
        new Paragraph(" "),
        new Paragraph("- Property: Requires division"),
        new Paragraph("- Support: Child and spousal support likely"),
        new Paragraph("- Timeline: Estimated 6–9 months"),
        new Paragraph("- Recommendations: Consider mediation, income reassessment"),
        new Paragraph(" "),
        new Paragraph("Chart Analysis:"),
        Media.addImage(doc, chartBuffer),
        new Paragraph("Report powered by Divorcepath API"),
      ],
    });

    // Convert the document to a Word buffer
    const buffer = await Packer.toBuffer(doc);

    // Return the Word document as a response
    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    res.setHeader("Content-Disposition", "attachment; filename=divorce-report.docx");
    res.send(buffer);

  } catch (err) {
    console.error("Error generating Word report:", err.stack || err);
    res.status(500).json({ error: "Failed to generate Word document", details: err.message });
  }
};
